package com.example.storepromax.domain.model

data class Order(
    val id: String = "",
    val userId: String = "",
    val items: List<CartItem> = emptyList(),
    val totalPrice: Long = 0,
    val totalCostPrice: Long = 0,
    val totalProfit: Long = 0,
    val receiverName: String = "",
    val receiverPhone: String = "",
    val address: String = "",
    val shippingMethod: String = "STANDARD",
    val status: String = "PENDING",
    val paymentMethod: String = "COD",
    val paymentStatus: String = "UNPAID",
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val discountCode: String? = null,
    val freeshipCode: String? = null,
    val cancelReason: String? = null,
    val cancelledBy: String = "",
    val returnReason: String? = null,
    val returnDescription: String? = null,
    val returnImages: List<String> = emptyList(),
    val returnTrackingCode: String? = null,
    val refundBankBin: String? = null,
    val refundBankShortName: String? = null,
    val refundAccountNumber: String? = null,
    val refundAccountName: String? = null,
    val refundReceiptUrl: String? = null,
    val reviewedProducts: List<String> = emptyList()
)